"""empty message

Revision ID: cc85e3242f03
Revises: d7ca92075815
Create Date: 2018-04-02 16:36:26.132293

"""

# revision identifiers, used by Alembic.
revision = 'cc85e3242f03'
down_revision = 'd7ca92075815'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.String(length=100), nullable=False))
    op.alter_column('comments', 'author',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('comments', 'author',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###
