"""empty message

Revision ID: d7ca92075815
Revises: 21ef9c07b9f7
Create Date: 2018-03-27 20:30:07.944263

"""

# revision identifiers, used by Alembic.
revision = 'd7ca92075815'
down_revision = '21ef9c07b9f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'tag_id')
    op.drop_table('tags')
    # ### end Alembic commands ###
