"""empty message

Revision ID: e236eab437ac
Revises: d7ca92075815
Create Date: 2018-03-30 21:56:31.842653

"""

# revision identifiers, used by Alembic.
revision = 'e236eab437ac'
down_revision = 'd7ca92075815'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author', sa.String(length=50), nullable=True))
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author'], ['id'])
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_2', 'comments', 'users', ['author_id'], ['id'])
    op.drop_column('comments', 'author')
    # ### end Alembic commands ###
